using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Praksa.Infrastructure.Persistence;

#nullable disable

namespace Praksa.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260621120000_AddDocumentTemplates")]
public partial class AddDocumentTemplates : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS document_templates (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code character varying(100) NOT NULL,
                name character varying(300) NOT NULL,
                description character varying(1000) NULL,
                category character varying(50) NOT NULL,
                file_name character varying(300) NOT NULL,
                content_type character varying(100) NOT NULL,
                file_size bigint NOT NULL,
                storage_path character varying(500) NOT NULL,
                sort_order integer NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                allowed_roles character varying(500) NULL,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NULL
            );
            """);

        migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS ix_document_templates_code ON document_templates (code);");
        migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS ix_document_templates_category ON document_templates (category);");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "document_templates");
    }
}
