using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Praksa.Infrastructure.Persistence;

#nullable disable

namespace Praksa.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260619120000_AddQuoteRequests")]
public partial class AddQuoteRequests : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS quote_requests (
                id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                appraisal_order_id  integer NOT NULL,
                appraiser_id        integer NOT NULL,
                status              integer NOT NULL DEFAULT 0,
                sent_at             timestamp with time zone NOT NULL,
                deadline            timestamp with time zone NOT NULL,
                sent_by_user_id     character varying(100),
                offered_price       numeric(18,2),
                offered_days        integer,
                responded_at        timestamp with time zone,
                thank_you_sent_at   timestamp with time zone,
                created_at          timestamp with time zone NOT NULL,
                updated_at          timestamp with time zone
            );

            CREATE INDEX IF NOT EXISTS ix_quote_requests_appraisal_order_id
                ON quote_requests (appraisal_order_id);

            CREATE UNIQUE INDEX IF NOT EXISTS ix_quote_requests_order_appraiser
                ON quote_requests (appraisal_order_id, appraiser_id);
        ");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS quote_requests;");
    }
}
