// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Praksa.Infrastructure.Persistence;

#nullable disable

namespace Praksa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603120000_AddCoreBusinessEntities")]
    partial class AddCoreBusinessEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
